name: Docker Build & Push

on:
  push:
    branches:
      - main   
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 🔹 API
      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rt-kanban-api:latest
            ghcr.io/${{ github.repository_owner }}/rt-kanban-api:${{ github.sha }}

      # 🔹 WEB
      - name: Build & Push Web
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rt-kanban-web:latest
            ghcr.io/${{ github.repository_owner }}/rt-kanban-web:${{ github.sha }}
